from app.schemas.generated_test import GeneratedTestArtifact

class Validator:
    """Validates the generated test artifact."""
    
    def validate(self, artifact: any) -> GeneratedTestArtifact:
        if not isinstance(artifact, GeneratedTestArtifact):
            raise ValueError(f"Expected GeneratedTestArtifact, got {type(artifact)}")
            
        if not artifact.generated_files:
            raise ValueError("No files were generated by the LLM.")
            
        seen_paths = set()
        for f in artifact.generated_files:
            if f.path in seen_paths:
                raise ValueError(f"Duplicate filename generated: {f.path}")
            seen_paths.add(f.path)
            
            if len(f.content.strip()) < 10:
                raise ValueError(f"Generated file {f.path} is essentially empty.")
                
        return artifact
